#!/bin/sh

# check number of arguments
if [ $# -ne 1 ];
    then
	echo -e "Usage: "$0" <machine>"
	exit 127
fi

# check to see if target directory exists
if [ -d $1 ]; 
    then
	cp $1/machine version
	if [ -d target ]; then
	    rm target
	fi
	ln -s $1 target
	. target/environ.sh
    else
	echo -e "Cannot target machine \""$1"\""
	exit 126
    fi

exit 0
